In [1]:
import random
from random import shuffle

In [4]:
x = [1,2,3,4,5]
shuffle(x)
x

[5, 4, 1, 2, 3]

In [8]:
for i in range(0,5):
    print(random.randint(1,10))

2
2
1
3
10


### Or the random numbers can be generated using numpy as well:

In [9]:
import numpy

In [10]:
# Gives the 3 X 5 random numbers with standard normal distribution
numpy.random.randn(3,5)

array([[ 0.38781084,  1.63806333, -0.07628073, -1.92821089, -0.52227168],
       [ 1.12796295, -1.41015291,  0.48517316, -1.02184128, -0.7986044 ],
       [-0.13991837, -0.11433185,  0.3505345 , -0.14845337, -0.68154542]])

In [12]:
# 1D
numpy.random.randn(3)

array([ 0.55707298, -0.70113091, -1.12963491])

In [11]:
# Gives the random numbers from the uniform range:
numpy.random.rand(3,5)

array([[0.4704666 , 0.17672521, 0.29937872, 0.42104692, 0.84963634],
       [0.38098405, 0.99865752, 0.11951507, 0.99445888, 0.2831334 ],
       [0.37069798, 0.14108252, 0.44643342, 0.96255298, 0.95135847]])

In [13]:
# 1 D
numpy.random.rand(3)

array([0.28492357, 0.72766491, 0.27643548])

In [19]:
# For integers between 3 and 10:
for i in range(0,5):
    print(numpy.random.randint(3,10))

6
3
4
6
7
